---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
   app: dev
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports: 
        - protocol: TCP
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  labels:
    app: dev
    env: qa
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    app: dev