---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web 
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports: 
        - protocol: TCP
          containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    app: web
  